apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    name: {{ .Values.config.name }}
data:
  {{- range .Values.config.data }}
  {{ .key }}: {{ .value }}
  {{- end}}