apiVersion: apps/v1
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: {{ .Values.app.name }}                    # Name of the Kubernetes resource
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}                                     # Number of pods to run at any given time
  selector:
    matchLabels:
      app: {{ .Values.app.name }}                 # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: {{ .Values.app.name }}
    spec:                                         # Spec for the container which will run in the Pod
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}       # The image we are getting from dockerhub
          imagePullPolicy: IfNotPresent             # If we have not pulled it before, get it from dockerhub
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports }}                   # Should match the port number that the Go application listens on

          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
            - configMapRef:
                name: {{ .Values.config.name }}
          env:
            {{- range .Values.config.data }}
            - name: {{ .key}}
              value: {{ .value}}
            {{- end}}

## ingress rules