apiVersion: v1
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: {{ .Values.app.name }}                # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.service.type }}                              # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: {{ .Values.app.name }}               # Selects any Pod with labels `app`
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}