replicaCount: 1
postgres:
  name: postgres
  group: db
  container:
    image: postgres:12.10-alpine
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    pvc:
      name: postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 1Gi
  config:
    name: postgres-config
    data:
      - key: DB_HOST
        value: postgres
      - key: POSTGRES_DB
        value: otus_2
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        value: password